language: cpp

# Use containers
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
    packages:
      - llvm-3.6-dev

compiler:
  - clang

script:
  - make test

notifications:
  email: false
